openapi: "3.0.1"
info:
  title: "tasks-api"
  version: "1.0"
paths:
  /list:
    get:
      summary: "List tasks"
      description: "Return a list of tasks"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                type: array
        500:
          description: "Internal Server Error"
          content: {}

      x-amazon-apigateway-integration:
        uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${ListTasksFunction.Arn}/invocations
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        contentHandling: "CONVERT_TO_TEXT"
        type: "aws_proxy"
